author: "Tobe O <thosakwe@gmail.com>"
description: "Turn an Angel service into a GraphQL API by calling one function."
homepage: "https://github.com/angel-dart/graphql"
name: "angel_graphql"
version: "1.0.0-alpha"
dependencies: 
  angel_framework: "^1.0.0"
  angel_validate: "^1.0.0"
  graphql: "^1.0.0-alpha"
  graphql_parser: "^1.0.0"
  graphql_schema: "^1.0.0-beta"
  resource: "^2.0.0"
dependency_overrides: 
  graphql: 
    git: "https://github.com/thosakwe/graphql.git"
dev_dependencies: 
  angel_hot: "^1.0.0"
  angel_test: "^1.0.0"
  console: "^2.2.4"
  test: "^0.12.0"
environment: 
  sdk: ">=1.19.0"
