name: angel_graphql
version: 1.0.0-alpha
description: Turn an Angel service into a GraphQL API by calling one function.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/graphql
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.0.0
  angel_validate: ^1.0.0
  graphql: ^1.0.0-alpha
  graphql_schema: ^1.0.0-beta
dev_dependencies:
  angel_hot: ^1.0.0
  angel_test: ^1.0.0
  test: ^0.12.0
dependency_overrides:
  graphql:
    path: ../../Dart/graphql_dart